### ISSUE TITLE
distance_to_roundabout in Preprocess_roudD is not defined

### ISSUE THREAD

**Issue by Alex-supreme5** [m-hasan-n/roundabout#1]
Hi Professor Hasan,

I had some problems when I ran Preprocess_roudD. Please see this issue below.

>> preprocess_roudD
The function or variable 'distance_to_roundabout' is not recognized

mistake preprocess_roudD>save_dataset_mat (line 452)
        dist_round = distance_to_roundabout(veh_traj, veh_lane_ids);

mistake preprocess_roudD (line 28)
save_dataset_mat(dataset_dir);

![mistake](https://user-images.githubusercontent.com/87303622/190133752-ab126c76-cb80-48cf-a867-e188f87a0db1.jpg)

Please help me with this issue.
Thanks a lot.

**Comment by m-hasan-n** [comment]
Hello, 
Thanks for your interest in our work and raising this important issue. I have just updated the script adding the missing function. Please check and let me know if there are any other issues.
